### ISSUE TITLE
Which version of "go-sql-driver/mysql" is used?

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bbs#22]
To connect to Azure Database for MySql, `allowNativePasswords=true` has to be used in the [connection string](https://github.com/cloudfoundry/diego-release/blob/v1.22.0/jobs/bbs/spec#L118). But I got the following error:

```
{"timestamp":"1501432342.563206196","source":"bbs","message":"bbs.sql-failed-to-connect","log_level":3,"data":{"error":"this authentication plugin is not supported","trace":"goroutine 1 [running]:\ncode.cloudfoundry.org/lager.(*logger).Fatal(0xc42005ce40, 0xdc30a1, 0x15, 0x119ba00, 0xc42014af90, 0x0, 0x0, 0x0)\n\t/var/vcap/packages/bbs/src/code.cloudfoundry.org/lager/logger.go:131 +0xc7\nmain.main()\n\t/var/vcap/packages/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:160 +0x4304\n"}}
```

I notice that the plugin `mysql_native_password` is only supported after this [commit](https://github.com/go-sql-driver/mysql/commit/ce924a41eea897745442daaa1739089b0f3f561d).
So, which version of `go-sql-driver/mysql` is used in `bbs`? Thanks in advance.

**Comment by bingosummer** [comment]
I figured it out. The version of `bbs` I was testing is `1.22.0` which used an older version of `go-sql-driver/mysql` which didn't support `mysql_native_password`.
I believe, `bbs 1.23.0` should work because the `mysql` has been upgraded to the latest version.
