### ISSUE TITLE
BBS reported an error when re-deployed cloud foundry to old version

### ISSUE THREAD

**Issue by norshtein** [cloudfoundry/bbs#32]
Hi, I'm using cloud foundry on Azure. I have a running cloud foundry environment deployed with [manifest v1.31.0](https://github.com/cloudfoundry/cf-deployment/blob/1bf516e1fffd86002d92d1d8c016d541c9d7a95b/cf-deployment.yml), and I need to change it to an old version. I re-deployed cloud foundry using [manifest v1.27.0](https://github.com/cloudfoundry/cf-deployment/blob/68e73dcf9741f8a7bf6f83e432257abc025c19b6/cf-deployment.yml). The deploy command is:
```
bosh -n -d cf deploy ~/example_manifests/cf-deployment.yml \
  --vars-store=~/cf-deployment-vars.yml \
  -o ~/example_manifests/azure.yml \
  -o ~/example_manifests/use-compiled-releases.yml \
  -o ~/example_manifests/use-azure-storage-blobstore.yml \
  -v system_domain=mydomain.com \
  -v environment=AzureCloud \
  -v blobstore_storage_account_name=mystorageaccount \
  -v blobstore_storage_access_key=mykey \
  -v app_package_directory_key=cc-packages \
  -v buildpack_directory_key=cc-buildpack \
  -v droplet_directory_key=cc-droplet \
  -v resource_directory_key=cc-resource

```
[Here](https://github.com/Azure/azure-quickstart-templates/tree/305f1274a1b4d8ff48c90bde53e2ed936c76972d/bosh-setup/manifests) is manifests I used. 

But then I got an error: `Error: 'diego-api/b3012abf-5cf9-4d27-979f-3f8f7df46926 (0)' is not running after update. Review logs for failed jobs: bbs`. In vm diego-api, I found `/var/vcap/sys/log/bbs/bbs.stderr.log` :
```
2018/05/21 09:18:03 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:3458: connect: connection refused"; Reconnecting to {localhost:3458 <nil>}
2018/05/21 09:18:04 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:3458: connect: connection refused"; Reconnecting to {localhost:3458 <nil>}
2018/05/21 09:18:06 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:3458: connect: connection refused"; Reconnecting to {localhost:3458 <nil>}
panic: context deadline exceeded

goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc4200d8420, 0xb8aa71, 0x1e, 0xbf57a0, 0xf64220, 0x0, 0x0, 0x0)
        /var/vcap/packages/bbs/src/code.cloudfoundry.org/lager/logger.go:162 +0x60f
main.main()
        /var/vcap/packages/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:271 +0x2f92
2018/05/22 02:35:15 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.1.16.7:8891: operation was canceled"; Reconnecting to {locket.service.cf.internal:8891 <nil>}
panic: context deadline exceeded

goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc42007e0c0, 0xb8aa71, 0x1e, 0xbf57a0, 0xf64220, 0x0, 0x0, 0x0)
        /var/vcap/packages/bbs/src/code.cloudfoundry.org/lager/logger.go:162 +0x60f
main.main()
        /var/vcap/packages/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:228 +0x35a4

```
And `/var/vcap/sys/log/bbs/bbs.stdout.log` : 
```
{"timestamp":"1526894283.917662621","source":"bbs","message":"bbs.starting","log_level":1,"data":{}}
{"timestamp":"1526894285.770040512","source":"bbs","message":"bbs.report-interval","log_level":1,"data":{"value":"1m0s"}}
{"timestamp":"1526894285.770769835","source":"bbs","message":"bbs.file-descriptor-notifier.starting","log_level":1,"data":{"session":"2"}}
{"timestamp":"1526894285.770853281","source":"bbs","message":"bbs.file-descriptor-notifier.started","log_level":1,"data":{"session":"2"}}
{"timestamp":"1526894285.770989418","source":"bbs","message":"bbs.lock-held-metrics-notifier.started","log_level":1,"data":{"session":"3"}}
{"timestamp":"1526894285.771057606","source":"bbs","message":"bbs.consul-lock.starting","log_level":1,"data":{"key":"v1/locks/bbs_lock","session":"4","value":"{\"id\":\"704d9b79-cfcd-4978-4679-396bd58bf943\",\"url\":\"https://diego-api-1.bbs.service.cf.internal:8889\"}"}}
{"timestamp":"1526894285.771183252","source":"bbs","message":"bbs.consul-lock.acquiring-lock","log_level":1,"data":{"key":"v1/locks/bbs_lock","session":"4","value":"{\"id\":\"704d9b79-cfcd-4978-4679-396bd58bf943\",\"url\":\"https://diego-api-1.bbs.service.cf.internal:8889\"}"}}
{"timestamp":"1526894286.272599459","source":"bbs","message":"bbs.consul-lock.acquire-lock-succeeded","log_level":1,"data":{"key":"v1/locks/bbs_lock","session":"4","value":"{\"id\":\"704d9b79-cfcd-4978-4679-396bd58bf943\",\"url\":\"https://diego-api-1.bbs.service.cf.internal:8889\"}"}}
{"timestamp":"1526894286.272719383","source":"bbs","message":"bbs.consul-lock.started","log_level":1,"data":{"key":"v1/locks/bbs_lock","session":"4","value":"{\"id\":\"704d9b79-cfcd-4978-4679-396bd58bf943\",\"url\":\"https://diego-api-1.bbs.service.cf.internal:8889\"}"}}
{"timestamp":"1526894286.273234606","source":"bbs","message":"bbs.locket-lock.started","log_level":1,"data":{"lock":{"key":"bbs","owner":"5a8f93ae-21b2-4e65-8dd2-9de61f50c7f8","type":"lock","type_code":1},"session":"5","ttl_in_seconds":15}}
{"timestamp":"1526894286.396898270","source":"bbs","message":"bbs.locket-lock.acquired-lock","log_level":1,"data":{"lock":{"key":"bbs","owner":"5a8f93ae-21b2-4e65-8dd2-9de61f50c7f8","type":"lock","type_code":1},"session":"5","ttl_in_seconds":15}}
{"timestamp":"1526894286.397058725","source":"bbs","message":"bbs.set-lock-held-metron-notifier.started","log_level":1,"data":{"session":"6"}}
{"timestamp":"1526894286.397238493","source":"bbs","message":"bbs.task-completion-workpool.starting","log_level":1,"data":{"session":"1"}}
{"timestamp":"1526894286.397336006","source":"bbs","message":"bbs.task-completion-workpool.started","log_level":1,"data":{"session":"1"}}
{"timestamp":"1526894286.399838924","source":"bbs","message":"bbs.migration-manager.starting","log_level":1,"data":{"session":"7"}}
{"timestamp":"1526894286.793093681","source":"bbs","message":"bbs.task-completion-workpool.finished","log_level":1,"data":{"session":"1"}}
{"timestamp":"1526894286.793245792","source":"bbs","message":"bbs.set-lock-held-metron-notifier.exited","log_level":1,"data":{"session":"6"}}
{"timestamp":"1526894286.793324232","source":"bbs","message":"bbs.locket-lock.signalled","log_level":1,"data":{"lock":{"key":"bbs","owner":"5a8f93ae-21b2-4e65-8dd2-9de61f50c7f8","type":"lock","type_code":1},"session":"5","signal":2,"ttl_in_seconds":15}}
{"timestamp":"1526894286.917878866","source":"bbs","message":"bbs.locket-lock.released-lock","log_level":1,"data":{"lock":{"key":"bbs","owner":"5a8f93ae-21b2-4e65-8dd2-9de61f50c7f8","type":"lock","type_code":1},"session":"5","ttl_in_seconds":15}}
{"timestamp":"1526894286.918073654","source":"bbs","message":"bbs.locket-lock.completed","log_level":1,"data":{"lock":{"key":"bbs","owner":"5a8f93ae-21b2-4e65-8dd2-9de61f50c7f8","type":"lock","type_code":1},"session":"5","ttl_in_seconds":15}}
{"timestamp":"1526894286.918158531","source":"bbs","message":"bbs.consul-lock.shutting-down","log_level":1,"data":{"key":"v1/locks/bbs_lock","received-signal":2,"session":"4","value":"{\"id\":\"704d9b79-cfcd-4978-4679-396bd58bf943\",\"url\":\"https://diego-api-1.bbs.service.cf.internal:8889\"}"}}
{"timestamp":"1526894287.077366114","source":"bbs","message":"bbs.consul-lock.done","log_level":1,"data":{"key":"v1/locks/bbs_lock","session":"4","value":"{\"id\":\"704d9b79-cfcd-4978-4679-396bd58bf943\",\"url\":\"https://diego-api-1.bbs.service.cf.internal:8889\"}"}}
{"timestamp":"1526894287.077541828","source":"bbs","message":"bbs.lock-held-metrics-notifier.finished","log_level":1,"data":{"session":"3"}}
{"timestamp":"1526894287.077660561","source":"bbs","message":"bbs.file-descriptor-notifier.finished","log_level":1,"data":{"session":"2"}}
{"timestamp":"1526894287.077957153","source":"bbs","message":"bbs.started","log_level":1,"data":{}}
{"timestamp":"1526894287.078159332","source":"bbs","message":"bbs.exited-with-failure","log_level":2,"data":{"error":"Exit trace for group:\nmigration-manager exited with error: Existing DB version (1523050077) exceeds bbs version (1502289152)\nserver exited with nil\nworkpool exited with nil\nset-lock-held-metrics exited with nil\nlock exited with nil\nlock-held-metrics exited with nil\nperiodic-filedescriptor-metrics exited with nil\ntask-stat-metron-notifier exited with nil\nhealthcheck exited with nil\ndebug-server exited with nil\n"}}

```
It seems the error is caused by incorrect DB version, I have no further idea on how to fix the error, could you have a look?

**Comment by emalm** [comment]
Hi, @norshtein, 

From the `bbs.exited-with-failure` log line, the migration manager failed because the "Existing DB version (1523050077) exceeds bbs version (1502289152)". This is because the cf-deployment versions you mentioned upgrade Diego from v2.4.0 to v2.6.0 and the BBS then executes the migrations at [1522700600_add_task_rejection_count.go](https://github.com/cloudfoundry/bbs/blob/master/db/migrations/1522700600_add_task_rejection_count.go) and [1523050077_add_rejection_reason_to_task.go](https://github.com/cloudfoundry/bbs/blob/master/db/migrations/1523050077_add_rejection_reason_to_task.go), which increment the version number in the Diego database. This version number increase makes previous BBS versions incompatible with the data schema, to maintain consistency of the data stored in the database.

Diego does not support any down migrations for the BBS DB schema in order to do a rollback. In a CF context, though, the Diego BBS database is effectively a cache derived from the apps in CCDB and the running app containers. Consequently, you can drop the BBS tables in the Diego schema and restart the BBS, and the following will happen:

- The BBS will recreate the data schema that matches its code version,
- The cell reps will continue to run their app instances and will recreate their corresponding ActualLRP records in the BBS DB,
- The CC clock will recreate the DesiredLRPs for the CF apps and then will set the `cf-apps` Domain record once it has finished creating all of the app records. 

In particular, the BBS will not destroy those ActualLRPs and the associated app instances during its LRP convergence operations until it knows via the presence of that `cf-apps` Domain that it has a complete set of DesiredLRPs for the apps. So the app instances will continue to run, although if they crash Diego will not restart new instances of them until CC submits a new DesiredLRP record for the app.

Any Tasks that happen to be running then will fail, though, and CF SSH will fail for app containers that existed before the database reset because CC has to regenerate SSH keys for the DesiredLRPs, which then no longer match the keys in the containers. To re-establish CF SSH connectivity to all app containers, though, you can force all the containers to be recreated though a BOSH update or restart of all the Diego cell VMs in the deployment.

Best,
Eric, CF Diego PM
